### ISSUE TITLE
Refactor manual_testing

### ISSUE THREAD

**Issue by chopan123** [soroswap/core#117]

**Comment by MattPoblete** [comment]
test

**Comment by MattPoblete** [comment]
Titles now displaying on purple

![Image](https://github.com/soroswap/core/assets/86752543/454d57c4-89f0-4533-bf29-633b71e84094)



![Image](https://github.com/soroswap/core/assets/86752543/fdd2d182-7276-4cc7-93d5-90faf532580c)



![Image](https://github.com/soroswap/core/assets/86752543/c096c392-f489-490f-b122-6686454c8512)




![Image](https://github.com/soroswap/core/assets/86752543/8389fb08-16d8-4a15-b341-8474cd3a821d)

**Comment by esteblock** [comment]
@MattPoblete 
Podrías crear una función que sea como 
fn check_user_balance(user, [token0_address, token_1_address, ...]), que agarre una lista de tokens y los termine mostrando de esa manera?
Porque varias veces se usa lo mismo después

**Comment by MattPoblete** [comment]
A function has been implemented to create tables that display the effects of the tests.


![Image](https://github.com/soroswap/core/assets/86752543/4229f6d5-3b61-4025-9b89-f80c400ea814)



![Image](https://github.com/soroswap/core/assets/86752543/b00ebc90-0738-48e2-b1b9-49c64e7fbfb0)



![Image](https://github.com/soroswap/core/assets/86752543/b6d6771a-75af-42f8-992d-30c694b0d8bd)



![Image](https://github.com/soroswap/core/assets/86752543/a0c8ed1b-95cf-4675-8c14-8da3aa3d07ae)
