### ISSUE TITLE
OS-SWP-SUG-02 | Unnecessary Authorization For Token Transfer

### ISSUE THREAD

**Issue by esteblock** [soroswap/core#121]
Unnecessary authorization required in the Router (https://github.com/soroswap/core/blob/main/contracts/router/src/lib.rs#L433) can lead to phishing attacks against users. 

When require_auth is used during the root invocation, it's assumed by Soroban that the address has authorized every subsequent call. If the provided token is malicious, it can gain authorization to steal the entire balance of any token from the user during the token.transfer external call. 

It's advisable to use token.transfer_from instead, which eliminates the need for require_auth.

**Comment by joaquinsoza** [comment]
#156

**Comment by esteblock** [comment]
Wont implement this as SDF recommendation is to use require_auth at the root
