### ISSUE TITLE
OS-SWP-SUG-00 | Integer Overflow

### ISSUE THREAD

**Issue by esteblock** [soroswap/core#123]
Consider implementing protection against integer overflow in the “receive_balance” function (https://github.com/soroswap/core/blob/main/contracts/pair/src/soroswap_pair_token/balance.rs#L24-L27).

**Comment by esteblock** [comment]
@joaquinsoza please write an article about the sollution and create PR

**Comment by joaquinsoza** [comment]
PR: #151

**Comment by joaquinsoza** [comment]
Article: [Ensuring Robustness Against Integer Overflow](https://github.com/soroswap/articles/blob/main/audit-review/IntegerOverflow.md)
