### ISSUE TITLE
OS-SWP-SUG-01 | Missing Address Check

### ISSUE THREAD

**Issue by esteblock** [soroswap/core#124]
Consider adding the same address check in the “Pair::new” (https://github.com/soroswap/core/blob/main/contracts/factory/src/pair.rs#L13) function. This will ensure "get_pair" (https://github.com/soroswap/core/blob/main/contracts/factory/src/lib.rs#L211) and “pair_exists” (https://github.com/soroswap/core/blob/main/contracts/factory/src/lib.rs#L251) functions fail early, providing protection against any undesired behavior.

**Comment by esteblock** [comment]
@joaquinsoza please check OS-SWP-SUG-01, write an article in "articles" repo about this, and create a PR to solve

**Comment by joaquinsoza** [comment]
#146
