### ISSUE TITLE
Script to add liquidity to several pairs

### ISSUE THREAD

**Issue by chopan123** [soroswap/core#132]
We need to create different paths for swaps in order to test the algorithm of finding the best path.

Then, complete the following tasks:
- [x] create a file to add liquidity to several pairs.
- [x] Select 2 tokens to build the paths. We will name those tokens: token A, token F
- [x] For a given 2 tokens, add liquidity to have 3 different paths. For example: path1: A->F, path2 A->B->F path3: A->C->D->F
- [x] Do the math behind to know _a priori_ which is the best path.
- [x] Adjust the amounts for the add liquidity to match the math
- [x] add a step to the script `deploy_tokens_n_pairs.sh` to add liquidity to several pairs.

**Comment by chopan123** [comment]
Math related:
$$m_1 = \frac{{m_0^\epsilon \cdot R_1}}{{R_0 + m_0^\epsilon}}$$

donde:
$m_0$ amount in token 0
$m_1$ amount out token 1
$\epsilon$ fee
$m_0^\epsilon=m_0\dot(1-\epsilon)$ amount with applied fee
$R_0$ Reserve of token 0
$R_1$ Reserve of token 1

**Comment by MattPoblete** [comment]
![image](https://github.com/soroswap/core/assets/86752543/33c32862-539c-4892-9383-7a6298df04ea)


The script to add liquidity to multiple paths, making the longest path the most profitable, was created successfully.

**Comment by esteblock** [comment]
Please make a refactor to execute everything in a 
populate.sh script
