### ISSUE TITLE
Core: Refactor deploy_tokens_n_pairs.sh

### ISSUE THREAD

**Issue by joaquinsoza** [soroswap/core#139]
We need a refactor of core/script

There is no meaning to have a deploy_tokens_n_pairs script if this is deploying token, issuing classic assets, wrapping classic tokens, setting up router, providing liquidity

**Comment by esteblock** [comment]
Script should be called populate_network.sh and receives network as parameter
- calls the deploy_tokens
- calls the add_liquidity script

**Comment by MattPoblete** [comment]
- Created script to populate the network
- Updated step 2 of README.md

![Image](https://github.com/soroswap/core/assets/86752543/f33e3e66-586a-4d70-a898-06a6da15e398)
