### ISSUE TITLE
Set trustline for recently added tokens

### ISSUE THREAD

**Issue by chopan123** [soroswap/core#199]
Current script set trustlines to all tokens from a list.

But, when a token is added to the list we need a script to set trustline only to the new token list.

See `scripts/see_trustline.ts` to get how to know if a token has trustline

**Comment by esteblock** [comment]
This can be done as a github action in the token-list repo.
We can set an env variable for the private key of the account that needs to have trustline to each asset, and when a new token list is added in the public token-list repo, triggers a set trustline function

**Comment by MattPoblete** [comment]
Please define TRUSTLINES_PRIVATE_KEY in tokens list repo @esteblock @chopan123 @joaquinsoza

**Comment by MattPoblete** [comment]
Workflow job is currently working on testnet!

![Image](https://github.com/soroswap/core/assets/86752543/d9a99d42-9a52-445a-8984-12828c4bd98b)

**Comment by MattPoblete** [comment]
> Please define TRUSTLINES_PRIVATE_KEY in tokens list repo [@esteblock](https://github.com/esteblock) [@chopan123](https://github.com/chopan123) [@joaquinsoza](https://github.com/joaquinsoza)

Remember to set the secret before merge the branch
