### ISSUE TITLE
Fix tokens api to use ethereum standard

### ISSUE THREAD

**Issue by joaquinsoza** [soroswap/core#56]
The tokens api and json file of tokens should be using the ethereum standard

This is ane xample json file of the tokens and how it should be.

https://tokens.coingecko.com/uniswap/all.json

**Comment by esteblock** [comment]
Follow https://discord.com/channels/897514728459468821/1162558946867953704

**Comment by esteblock** [comment]
- Token list will be hosted in a raw file in https://github.com/soroswap/token-list
- Core "populate_network" script should push new info into standalone section of token-list

**Comment by esteblock** [comment]
Using https://github.com/soroswap/token-list/
