### ISSUE TITLE
Force rust to use an specific version

### ISSUE THREAD

**Issue by esteblock** [soroswap/core#89]
#What?
When rust is being updated, we have a problem with soroban-preview because it cannot upgrade the rust version.

# Idea
Use
```
rustup default 1.73.0

pwd
# /src/
rustc --version
# rustc 1.73.0

cd dev
pwd
# /src/dev
rustup override set 1.68.0
rustc --version
# rustc 1.68.0

cd ..
rustc --version
# rustc 1.73.0
```

**Comment by esteblock** [comment]
This works...
```
cargo +1.74.1 build --target wasm32-unknown-unknown --release
```

**Comment by esteblock** [comment]
@joaquinsoza Not working

**Comment by joaquinsoza** [comment]
fixed by adding this to the Makefile
```
RUST_VERSION := $(shell rustc --version | cut -d ' ' -f 2)

build:
	cargo +$(RUST_VERSION) build --target wasm32-unknown-unknown --release
```

We should not merge the brunch until testing... The next rust update will be on February 8 so we can test the branch when the new rust version gets released

**Comment by joaquinsoza** [comment]
Caused errors when building for the first time... will need to find or test other ways to fix the rust version.

For now each time a new version of rust comes out we will need to update the docker image

**Comment by esteblock** [comment]
deleting the toolchain we are OK
